name: virtualfleet
channels:
  - conda-forge
dependencies:
  - python=3.6
  - xarray=0.16.0
  - parcels=2.1.4
  - dask
  - distributed
  - dask-kubernetes
  - gcsfs
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - nomkl
  - nbserverproxy
  - jupyter
  - jupyterlab=0.35
  - jupyterlab_launcher
  - jupyter_client
  - jupyter_server
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - graphviz
  - nodejs
  - scikit-image
  - scikit-learn
  - watermark
  - shapely
  - cartopy=0.19.0
  - pip
  - pip:
    - graphviz
    - jupyter-server-proxy
    - netCDF4
    - erddapy
    - gitpython
    - cmocean
    - git+http://github.com/euroargodev/argopy.git@master
    - progressbar
    - cgen
    - pymbolic
