name: virtualfleet-docs
channels:
  - conda-forge
dependencies:
  - python=3.9
  - xarray
  - parcels>=3.0.0
  - scipy
  - netcdf4
  - dask
  - toolz
  - erddapy
  - fsspec
  - gsw
  - aiohttp
  - bottleneck
  - cartopy
  - cftime
  - distributed
  - ipython
  - matplotlib
  - numpy
  - pandas
  - packaging
  - pip
  - pytest
  - seaborn
  - setuptools
  - zarr
  - tqdm
  - ipykernel
  - ipywidgets
  - nbsphinx
  - jinja2
  - sphinx-issues
  - sphinx_rtd_theme
  - sphinx-book-theme
  - codespell
  - cfgrib
  - black
  - flake8
  - pytest-cov
  - pytest-env
  - pip:
    - git+https://github.com/euroargodev/argopy.git@master
    - Sphinx
    - numpydoc
    - readthedocs-sphinx-ext
    - sphinx-autosummary-accessors
    - pydocstyle
    - cgen
    - pymbolic
    - Pydap
