name: virtualfleet-v3
channels:
  - conda-forge
dependencies:
  - python=3.9
  - xarray>0.16.0
  - parcels>=3.0.0
  - dask
  - distributed
  - dask-kubernetes
  - bottleneck
  - gcsfs
  - zarr
  - matplotlib
  - numcodecs
  - python-blosc
  - lz4
  - libzip
  - nomkl
#  - nbserverproxy
  - jupyter
  - jupyterlab>=0.35
  - jupyterlab_launcher
  - jupyter_client
  - jupyter_server
  - nb_conda_kernels
  - ipykernel
  - ipywidgets
  - graphviz
  - nodejs
  - scikit-image
  - scikit-learn
  - watermark
  - shapely
  - cartopy>=0.19.0
  - seaborn
  - xhistogram
  - tqdm
  - py
  - pip
  - pip:
    - git+https://github.com/euroargodev/argopy.git@master
    - jupyter-server-proxy
    - netCDF4
    - erddapy
    - gitpython
    - cmocean
    - progressbar
    - cgen
    - pymbolic
    - Pydap
