# pyproject.toml tells “frontend” build tools like pip and build what “backend” tool to use
# to create distribution packages for your project

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"