name: myenv
channels:
  - conda-forge
dependencies:
  # You need the pangeo-notebook conda-forge package in your environment.yml for compatibility with pangeo cloud deployments
  - pangeo-notebook==2021.09.30
  # The rest of the packages are up to you!
  - xarray
  - hvplot
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - cartopy
  - scikit-learn
  - seaborn
  - dask-ml
  - watermark
  - gsw
  - pip
  - pip:
    - gitpython
    - cmocean
    - sat-search
    - git+http://github.com/euroargodev/argopy.git@master
    - progressbar
    - cgen
    - pymbolic
    - git+https://github.com/OceanParcels/parcels.git@master

