#!/bin/bash

# you can add commands that run after building the environment here!
# https://repo2docker.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment

jupyter lab clean

# Import the workspace into JupyterLab
#jupyter lab workspaces import workspace.json
#jupyter lab workspaces import jupyterlab-workspace.json

#EOF
