#!/bin/bash -l

# ==== ONLY EDIT WITHIN THIS BLOCK =====

export PANGEO_ENV="BINDER_TEMPLATE"

cd /home/jovyan
mkdir data
cd data
wget https://api.ifremer.fr/virtualfleet/data/GLOBAL-ANALYSIS-FORECAST-PHY-001-024/2019-monthly.tar.gz
tar -xvf 2019-monthly.tar.gz
cd /home/jovyan

# ==== ONLY EDIT WITHIN THIS BLOCK =====

exec "$@"
