#!/bin/bash

# Replace DASK_DASHBOARD_URL with the proxy location
sed -i -e "s|DASK_DASHBOARD_URL|/user/${JUPYTERHUB_USER}/proxy/8787|g" binder/jupyterlab-workspace.json
# Get the right workspace ID
sed -i -e "s|WORKSPACE_ID|/user/${JUPYTERHUB_USER}/lab|g" binder/jupyterlab-workspace.json

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/jupyterlab-workspace.json \
  --NotebookApp.base_url=user/${JUPYTERHUB_USER}

# download data for tests
cd /home/jovyan
mkdir data
cd data
#wget https://storage.cloud.google.com/global-analysis-forecast-phy-001-024/20200627_global-analysis-forecast-phy-001-024.nc
wget https://storage.cloud.google.com/global-analysis-forecast-phy-001-024/2019-monthly.zip
cd -

exec "$@"
